git:
  # press | to cycle between pagers
  # delta themes defined in ~/dotfiles/delta/themes.gitconfig
  pagers:
    - colorArg: always
      pager: delta --features lazygit-side-by-side
    - colorArg: always
      pager: delta --features lazygit-inline
gui:
  theme:
    nerdFontsVersion: ""
    activeBorderColor:
      - green
      - bold
    inactiveBorderColor:
      - white
    # default: reverse (highlights with inverted colors)
    selectedLineBgColor:
      - "#303050"
    # default: green bg
    diffAddBgColor:
      - default
    # default: red bg
    diffRemoveBgColor:
      - default
    # default: green
    diffAddFgColor:
      - green
    # default: red
    diffRemoveFgColor:
      - red
